import React from 'react'
import { Providers } from '~/components/providers'
import { Geist } from "next/font/google";
import type { Metadata } from 'next';
import "~/styles/globals.css";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});
export const metadata: Metadata = {
  title: "Dukem music Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const DashboardLayout = ({
    children,
}: {
    children: React.ReactNode
}) => {
  return (
     <html lang="en" className={`${geist.variable}`}>
      <body>
        <Providers>
            <main className='flex-1 overflow-y-auto'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}

export default DashboardLayout